name: fcl_prod_2
channels:
  - pytorch
  - conda-forge
  - https://repo.prefix.dev/robotology
dependencies:
  - python=3.10
  - pysimplegui
  - opencv
  - ace
  - asio
  - assimp
  - libboost-devel
  - cli11
  - eigen
  - freetype
  - glew
  - glfw
  - glm
  - graphviz
  - gsl
  - "ipopt>3.13.0"
  - irrlicht 
  - libjpeg-turbo 
  - libmatio
  - libode
  - libxml2
  - nlohmann_json
  - qhull
  - "pcl>=1.11.1" 
  - "libopencv>=4.10.0"
  - opencv
  - portaudio
  - qt-main
  - sdl
  - sdl2
  - sqlite 
  - tinyxml 
  - tinyxml2
  - spdlog
  - lua
  - soxr
  - qhull
  - cmake
  - compilers
  - make
  - ninja
  - pkg-config
  - tomlplusplus
  - libzlib
  - ffmpeg
  - onnxruntime-cpp
  - bash-completion
  - freeglut
  - libdc1394
  - libi2c
  - xorg-libxau
  - libxcb 
  - xorg-libxdamage
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxxf86vm
  - xorg-libxrandr
  - libgl-devel
  - numpy
  - swig
  - pybind11
  - pyqt
  - matplotlib
  - h5py
  - tornado
  - u-msgpack-python
  - pyzmq
  - ipython
  - gst-plugins-good
  - gst-plugins-bad
  - pyqtwebengine 
  - qtpy
  - pyyaml
  - pip:
      - torch
      - torchvision
      - torchaudio
      - imageio
      - transformers
